M48
; DRILL file {KiCad 7.0.11+1} date dom 14 abr 2024 15:42:33
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-14T15:42:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1122
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X9.49Y-1.9
X9.49Y-5.4
T2
X6.44Y-2.8559
M30
